---
title: "Trees in Agriculture Policy Analysis"
author: "Lisa Meixner McCullough"
date: '2022-08-15'
output:
  word_document:
    toc: yes
  html_document:
    code_folding: hide
    theme: lumen
    highlight: espresso
    toc: yes
    number_section: yes
    toc_float: yes
    fig_width: 7
    fig_height: 6
    fig_caption: yes
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(knitr)
require(RColorBrewer)
```

# Document Purpose

1. Import tia1_policy_long
2. Make a custom histogram


# Import Data
```{r workbook, message=F}
#read csv
policy_long<-read_delim("tia1_policy_long.csv",delim=",",col_names=T)
policy_long<-policy_long%>%
  mutate_at(vars(reasonImportance),factor,levels=c("Not Meaningful","Last","Eighth","Seventh","Sixth","Fifth","Fourth","Third","Second","Top"))%>%
  mutate_at(vars(policyPriority),factor,levels=c("Not Meaningful","Last","Fifth","Fourth","Third","Second","Top"))

```


# Visualize Data
- Defaults
  - It will include responses for all continents and all biomes

1. Create Histogram Function

```{r function}
crop_histogram<-function(crop,data,what2plot,continent,biome){
    if(crop!="All"){
      if(crop=="corn"){
        data<-data%>%filter(crop=="corn")
        }
      if(crop=="wheat"){
        data<-data%>%filter(crop=="wheat")
        }
      if(crop=="soy"){
        data<-data%>%filter(crop=="soy")
        }
    }
    dimDistinct<-transmute(data,name=name,repTree=repTree)%>%distinct()%>%dim()
  numResp<-dimDistinct[1]

  data%>%
    filter(policy!="Other"&policy!="None"&!is.na(policy))%>%
    ggplot(mapping=aes(x=policy)) +
      geom_bar(position="fill",aes(fill=policyPriority))+
      coord_flip()+
      labs(y="Proportion of Reponses",x=what2plot,title="Expert Responses",subtitle=paste("Continent:",continent," Biome:",biome," Crop:",crop),caption=paste("Number of Unique Responses:",as.character(numResp)))+
      theme_minimal()+
      scale_fill_brewer(type="div",palette="RdYlBu",direction=-1,aesthetics=c("fill"))
}

```
2. Display plot for All Crops
```{r all crop plot}
#initialize defaults
what2plot<-"Policy"
continent<-"All"
biome<-"All"
var<-"policy"
fill<-"policyPriority"

crop_histogram(crop="All",data=policy_long,what2plot=what2plot,continent=continent,biome=biome)

```
2. Display plot for corn 
```{r corn crop plot}
#initialize defaults
what2plot<-"Policy"
continent<-"All"
biome<-"All"
var<-"policy"
fill<-"policyPriority"

crop_histogram(crop="corn",data=policy_long,what2plot=what2plot,continent=continent,biome=biome)

```

2. Display plot for wheat
```{r wheat crop plot}
#initialize defaults
what2plot<-"Policy"
continent<-"All"
biome<-"All"
var<-"policy"
fill<-"policyPriority"

crop_histogram(crop="wheat",data=policy_long,what2plot=what2plot,continent=continent,biome=biome)

```

2. Display plot for soy 
```{r soy crop plot}
#initialize defaults
what2plot<-"Policy"
continent<-"All"
biome<-"All"
var<-"policy"
fill<-"policyPriority"

crop_histogram(crop="soy",data=policy_long,what2plot=what2plot,continent=continent,biome=biome)

```
